### ISSUE TITLE
RegAlloc: Automate transfer between GPR and XMM registers

### ISSUE THREAD

**Issue by MerryMage** [MerryMage/dynarmic#55]
There is currently quite a lot of [manual transfer](https://github.com/MerryMage/dynarmic/blob/e166965f3e2a06761bd3421eb780e70cc1419dfd/src/backend_x64/emit_x64.cpp#L1248-L1252) going on in `emit_x64.cpp` between GPRs and XMM registers especially for the parallel instruction implementations. This is a wasteful use of FP bandwidth especially if there are a series of parallel instructions being executed in a row.

The register allocator could be more intelligent in this respect. 

**Potential issues:** The register allocator currently assumes that all `Value`s under its management in XMM and GPR registers must be of type F32/F64 only and U8/U16/U32/U64 only respectively.

**Comment by MerryMage** [comment]
**Reminder:** [TransferToFP32/TransferToFP64](https://github.com/MerryMage/dynarmic/blob/cede5e442ab19ddfdcb4c64163e3e52f7059329e/src/backend_x64/emit_x64.cpp#L1679-L1701) would becoming no-ops when this change is implemented.

**Comment by FernandoS27** [comment]
A summary of yesterday's discussion. A solution for this problem can be made using streaming/unstreaming as well as stream fusion. The idea is that all the vectorization instructions (ex VADD) are turned into 5 instructions on the IR: 2 x streams, main instruction, 2 x unstreams. Each stream represents a transfer from a register on the backend. The idea is to do an optimization pass on the IR to remove matching streams/unstreams since stream . unstream a = a. Such optimization pass would also delay unstreaming to it's last use within a block of code, thus saving the transfer to GPR to the last needed moment.

example of streaming <- stream(F32,2,[a,b])

These transformations also open the possibility for further optimizations like:
y1 <- stream(F32,2,[a,b])
y2 <-  stream(F32,2,[c,d])
y3 <- stream_add y1 y2
{r1,r2} <- unstream y3
y4 <- stream(F32,2,[e,f])
y5 <-  stream(F32,2,[g,h])
y6 <- stream_add y4 y5
{r3,r4} <- unstream y6
could be optimized to:
y1 <- stream(F32,4,[a,b,e,f])
y2 <-  stream(F32,4,[c,d,g,h])
y3 <- stream_add y1 y2
{r1,r2,r3,r4} <- unstream y3
this would use an appropiate SIMD instruction on host (SSE or AVX)

Papers:
https://pdfs.semanticscholar.org/64d2/a65a7d559f9b05570fb0fea8bb4cccd83ae2.pdf
https://www.microsoft.com/en-us/research/wp-content/uploads/2016/07/haskell-beats-C.pdf

**Comment by MerryMage** [comment]
Closed by 6396bd02f003d7a9e7d17aae51c5b31f1f4e8d39.
