### ISSUE TITLE
Unimplemented Instructions list

### ISSUE THREAD

**Issue by FernandoS27** [MerryMage/dynarmic#69]
# Unimplemented Instructions list

This list contains all the instructions which aren't being recompiled by the JIT and are sent into the interpreter. In order to optimize and improve the performance of the JIT, the further instructions must be implemented.

## Thumb

- [ ] UDF

## Exception generating

- [ ] BKPT
- [ ] UDF

## Load/Store (System Instructions)

- [ ] LDM_usr
- [ ] LDM_eret
- [ ] STM_usr
- [ ] LDRBT
- [ ] LDRHT
- [ ] LDRSBT
- [ ] LDRSHT
- [ ] LDRT
- [ ] STRBT
- [ ] STRHT
- [ ] STRT

## Parallel

- [x] QASX
- [x] QSAX
- [x] UQASX
- [x] UQSAX

## Status Register Access

- [ ] CPS
- [ ] RFE
- [ ] SRS

**Comment by lioncash** [comment]
Note that LDM (User) and LDM (Exception Return) are privileged mode load instructions. LDM (User) needs to be in a privileged mode other than system (because system shares registers with user mode), and LDM (Exception Return) would always be done from a privileged state (exception processor modes are privileged modes).

The other load/stores ending with `T` aren't necessarily privileged only (they can be used in unprivileged modes too, though equivalents without the `T` suffix are better in that case). All they do are just allow privileged modes to do loads and stores as if they're in user mode.

**Comment by MerryMage** [comment]
Related to #23.

**Comment by Dragios** [comment]
This list should be updated with the recent changes implemented. Not sure why these instructions is not in this list as well like QSASX, QSSAX, QUSAX, QUASX, UADD16, USAD8, USADA8 & other instruction list that I might have missed.

**Comment by MerryMage** [comment]
Updated.
